### ISSUE TITLE
Yardım

### ISSUE THREAD

**Issue by venti1337** [orhanayd/kandilli-rasathanesi-api#2]
Merhaba az önce kendi local'imde hostlamayı denediğimde server load ms değişkeninin değeri random ve hiçbir veri vermemektedir.

**Comment by orhanayd** [comment]
Merhabalar,
server load ms server tarafında ne kadar süre harcadığına dair bir ms değer. status eğer false dönüyorsa sunucu yoğunluğundan kaynaklanıyor olabilir.
1. status ne dönmekte ?
2. dönen cevabı yazabilir misiniz?

**Comment by orhanayd** [comment]
Ben yanlış anladım @venti1337 seni.
Kullanmak istersen ENV malasef paylaşamam fakat ilgili endpointlerden dataları kullabilirsin.
