### ISSUE TITLE
/deprem/int/earthquakes servisinde 500 hatası

### ISSUE THREAD

**Issue by phoique** [orhanayd/kandilli-rasathanesi-api#4]
Swagger üzerinden "/deprem/int/earthquakes" servisine istek atıldığında 
```
{
  "status": false,
  "httpStatus": 500,
  "desc": "missing systemid or authorization"
}
```
hatası veriyor bilginize.

**Comment by orhanayd** [comment]
Merhabalar,
Burası int cron endpoint'idir. Burası public kullanıma kapalıdır.
