### ISSUE TITLE
Koordinat hatası

### ISSUE THREAD

**Issue by Tali781** [orhanayd/kandilli-rasathanesi-api#6]
Long ve lat yer değiştirmesi gerekiyor

**Comment by orhanayd** [comment]
Merhabalar,
geojson da ki coordinates içinde ki 0 long 1 ise lat. Bunu mongoDB dökümanına göre hazırladım.
https://www.mongodb.com/docs/manual/reference/geojson/#geojson-objects
"If specifying latitude and longitude coordinates, list the longitude first, and then latitude.".

**Comment by orhanayd** [comment]
Konu için teşekkür ederim.

**Comment by Tali781** [comment]
Ama koordinat sisteminde önce enlem yani latitude girilir. Sizin API'nizin verdiği koordinatları arayınca yanlış yerler çıkıyor.

**Comment by orhanayd** [comment]
Evet ama bunu veritabanına göre tasarlamak zorundaydım.

**Comment by orhanayd** [comment]
Ayrıca RFC 7946 section3.1.1 de belirtilen Position standartına baktığımızda:
https://www.rfc-editor.org/rfc/rfc7946#section-3.1.1
yine long 0 . eleman.

**Comment by orhanayd** [comment]
Ayrıca;
Leaflet uses lat-lng (or northing-easting ) whereas GeoJSON uses lng-lat (or easting-northing). Burada yanlış bir kullanım yoktur yani.

**Comment by Tali781** [comment]
👍
