### ISSUE TITLE
Archive Data Limit

### ISSUE THREAD

**Issue by halilcn** [orhanayd/kandilli-rasathanesi-api#7]
Hi Orhan,

I want to get the data using archive API but I saw that you put a limit on the data. 
For example, I would like to get the data of the last 15 days, I couldn't get all data because you had put max 1000 data limit. Then I tried to get the data with more of a request, but I couldn't send more than 1000 skip params. As I examined the project, you limited that 😄 

Are there any else ways to get archive data?

**Comment by orhanayd** [comment]
Hi Halil,
Firstly thank you so much for interest this project. if I remove 1000 limit from skip param can be work for you ?

Best Regards,

**Comment by halilcn** [comment]
Yeah, it would resolve this issue but are there any special reasons for putting the limit to get data? Such as performance, etc.. 
Because if there isn't a limit to get data, we wouldn't need a skip parameter.

**Comment by orhanayd** [comment]
Yes I have reasons for limiting for response. First for performance. Because I'm working on small server and I want fast response for every request. if you have any idea I can do.

**Comment by halilcn** [comment]
I see, you are right 😄  I thought according to myself, because I will have to request a few times, but it is not important. If you can remove skip limit, it will satisfy me. 

By the way, I am trying to use your API on a map app, so I am trying to show the data on a map, thanks for API 💯

**Comment by orhanayd** [comment]
I create new branch for remove skip limit. Looks like a I will deploy today. I'm happy for your project. Please send me link/app I will follow. Thank you so much!

**Comment by halilcn** [comment]
I am gonna send the link after completing the ideas in my mind, thanksss!
